# <span style="color:blue">Diane Rodden</span>

# Various simulations of rolling 1 die
##    Uses: Python Jupyter Notebook
##    Includes: codes, results, discussion and an extension exercise

## Other notes
- The number of sides on the die and the lowest starting number on the die are stored in variables for flexibility
- The number of times that the die will be rolled is also stored in a variable so the value can be easily changed
- Assume a fair die

## Preliminaries

In [1]:
# Import libraries
import random
from collections import Counter
from math import sqrt
import statistics

In [2]:
# Set random seed for reproducibility
random.seed(607)

In [3]:
# Initialize values using the example of a 20 sided die, with lowest value 1 and highest value of 20

# Store number of sides on die
sides = 20

# Set starting number on die
lowest = 1

# Calculate highest number on die
highest =  lowest + sides - 1

In [4]:
# Also initialize the value for the number of rolls
n = 1

## Create functions

In [5]:
# Function to roll die r times and store results in list
def RollDieFunction(r):
    
    # Create a list to store the results of all of the rolls
    rollsList = []

    # Roll the die
    for i in range(r):
        result = random.randint(lowest, highest)
        rollsList.append(result)

    return rollsList;

In [6]:
# Function to print results
def PrintResultsFunction():
    print(f"The results of the {n} die rolls with a {sides}-sided die are:  {rollsList}");


In [7]:
# Function for a frequency distribtion to understand the data better
def FreqDistFunction():
    counts = Counter(rollsList)
    print(f"The frequency distribution is: {counts}");

In [8]:
# Function to get the average of the n die rolls 
def AverageFunction(): 
    return sum(rollsList) / len(rollsList);  

In [9]:
# Function to calculate standard deviation of the n die rolls manually
# IMPORTANT: Assumes that the die rolls are a sample of all the possible dice rolls in the population
def StdDevFunction():
    
    sumSqrdDiff = 0
    
    for j in rollsList:
        SqrdDiff = (j - theAverage)**2
        sumSqrdDiff = sumSqrdDiff + SqrdDiff
        
    theVariance = sumSqrdDiff / (len(rollsList) - 1)
                                   
    return sqrt(theVariance);

In [10]:
#  Function to double check standard deviation using  for the n die rolls
# IMPORTANT: Assumes that the die rolls are a sample of all the possible dice rolls in the population
def BuiltInStdDevFunction():
    theStdDev2 = statistics.stdev(rollsList)
    return theStdDev2;

## Call the die rolling, results, average and std deviation functions for 100 rolls of the die

In [11]:
n = 100

In [12]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the results
PrintResultsFunction()

The results of the 100 die rolls with a 20-sided die are:  [3, 4, 5, 11, 2, 6, 17, 8, 1, 6, 4, 15, 2, 15, 15, 10, 19, 20, 4, 3, 14, 8, 4, 14, 2, 2, 18, 20, 9, 10, 3, 8, 1, 5, 11, 1, 8, 6, 9, 18, 20, 6, 12, 14, 20, 20, 16, 14, 18, 16, 10, 17, 14, 13, 6, 7, 9, 12, 10, 17, 17, 14, 17, 2, 8, 5, 11, 7, 12, 12, 10, 7, 1, 9, 3, 15, 2, 12, 20, 20, 17, 10, 9, 18, 6, 15, 11, 20, 19, 15, 2, 8, 15, 7, 1, 15, 15, 12, 12, 11]


In [13]:
# Call the function to print the frequency distribution
FreqDistFunction()

The frequency distribution is: Counter({15: 9, 20: 8, 2: 7, 12: 7, 6: 6, 17: 6, 8: 6, 10: 6, 14: 6, 11: 5, 1: 5, 9: 5, 3: 4, 4: 4, 18: 4, 7: 4, 5: 3, 19: 2, 16: 2, 13: 1})


In [14]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

The average of 100 rolls of the die with a 20-sided die is 10.54.


In [15]:
# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")


# Call the built-in standard deviation function
theStdDev2 = BuiltInStdDevFunction()
print(f"Using the built-in standard deviation function for a sample, the standard deviation is {theStdDev2}.")

The standard deviation of the sample of 100 rolls of the die with a 20-sided die is 5.81433269141564.
Using the built-in standard deviation function for a sample, the standard deviation is 5.814332691415641.


## As a comparison, call the die rolling, results, average and std deviation functions for 5 rolls of the die

In [16]:
n = 5

In [17]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the results
PrintResultsFunction()

The results of the 5 die rolls with a 20-sided die are:  [13, 14, 15, 13, 2]


In [18]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")

The average of 5 rolls of the die with a 20-sided die is 11.4.
The standard deviation of the sample of 5 rolls of the die with a 20-sided die is 5.319774431308154.


## Next, call the die rolling, results, average and std deviation functions for 50 rolls of the die

In [19]:
n = 50

In [20]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the results
PrintResultsFunction()

The results of the 50 die rolls with a 20-sided die are:  [20, 16, 1, 11, 12, 15, 7, 11, 8, 8, 18, 9, 5, 15, 6, 8, 13, 20, 9, 19, 11, 20, 16, 20, 5, 14, 4, 10, 12, 4, 13, 18, 5, 5, 2, 3, 8, 10, 9, 1, 2, 17, 15, 5, 5, 10, 7, 9, 13, 19]


In [21]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")

The average of 50 rolls of the die with a 20-sided die is 10.46.
The standard deviation of the sample of 50 rolls of the die with a 20-sided die is 5.614158486381025.


## Then, call the die rolling, results, average and std deviation functions for 200 rolls of the die

In [22]:
n = 200

In [23]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the frequency distribution
FreqDistFunction()

The frequency distribution is: Counter({12: 16, 5: 12, 13: 12, 7: 12, 6: 12, 4: 11, 18: 11, 2: 10, 17: 10, 1: 10, 10: 10, 14: 9, 3: 9, 19: 9, 20: 9, 15: 9, 8: 8, 16: 8, 11: 7, 9: 6})


In [24]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")

The average of 200 rolls of the die with a 20-sided die is 10.34.
The standard deviation of the sample of 200 rolls of the die with a 20-sided die is 5.741885250608532.


## Now, call the die rolling, results, average and std deviation functions for 1,000 rolls of the die

In [25]:
n = 1000

In [26]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the frequency distribution
FreqDistFunction()

The frequency distribution is: Counter({19: 58, 3: 57, 13: 57, 4: 55, 8: 55, 5: 54, 6: 54, 1: 53, 20: 53, 12: 52, 14: 51, 15: 49, 18: 49, 9: 47, 2: 46, 11: 46, 16: 45, 17: 44, 7: 40, 10: 35})


In [27]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")

The average of 1000 rolls of the die with a 20-sided die is 10.455.
The standard deviation of the sample of 1000 rolls of the die with a 20-sided die is 5.86484197326503.


## Finally, call the die rolling, results, average and std deviation functions for 50,000 rolls of the die

In [28]:
n = 50000

In [29]:
# First call the function to roll die and store results in a list
rollsList = RollDieFunction(n)

# Call the function to print the frequency distribution
FreqDistFunction()

The frequency distribution is: Counter({2: 2566, 3: 2565, 8: 2554, 15: 2551, 16: 2529, 12: 2525, 4: 2520, 17: 2512, 14: 2512, 5: 2511, 19: 2502, 13: 2500, 6: 2492, 7: 2486, 20: 2472, 10: 2464, 9: 2462, 18: 2456, 11: 2433, 1: 2388})


In [30]:
# Call the function to find the average of the results
theAverage = AverageFunction()
print(f"The average of {n} rolls of the die with a {sides}-sided die is {theAverage}.")

# Call the manual standard deviation function
theStdDev = StdDevFunction()
print(f"The standard deviation of the sample of {n} rolls of the die with a {sides}-sided die is {theStdDev}.")

The average of 50000 rolls of the die with a 20-sided die is 10.49568.
The standard deviation of the sample of 50000 rolls of the die with a 20-sided die is 5.761392645055505.


## Expected value for a single roll of the same die

### The general formula for the expected value for a probability distribution is

E(x) =  ($x_{1}$ * p($x_{1}$))  + ($x_{2}$ * p($x_{2}$)) + ($x_{3}$ * p($x_{3}$)) + ...  for all of the possible values for x
     where p($x_{1}$) is the probability of $x_{1}$,  p($x_{2}$) is the probability of $x_{2}$ and so forth


For rolls of the die:
- p is 1/number of sides since this is a fair die
- The possible values of x are the values on the die. For instance, using a 6-sided die with lowest value of 1, the possible values of x are 1,2,3,4,5,6

In [31]:
# Calculations

# p
p = 1/sides

# Create a list of possible values of x

# Initialize list
possibleX = []

# Populate list
for k in range(lowest,highest+1):
    possibleX.append(k)

# Check list
print(f"The possible values of x are: {possibleX}")


# Find E(x)
ExpectedX = 0
for m in possibleX:
    ExpectedX = ExpectedX + (m * p)

    
print(f"The E(x) is: {ExpectedX}, which is the mean of the probability distribution")
print(f"of one roll of a {sides}-sided die")

The possible values of x are: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
The E(x) is: 10.5, which is the mean of the probability distribution
of one roll of a 20-sided die


# Standard deviation for a single roll of the die
    
### The formula for variance in general for a probability distribution is
Variance =( ($x_{1}$ - mu)$^{2}$  *  p($x_{1}$) )   +  ( ($x_{2}$ - mu)$^{2}$  *  p($x_{2}$) )  +  ( ($x_{3}$ - mu)$^{2}$  *  p($x_{3}$) )  +  ...


 for all of the possible values for x  where p($x_{1}$) is the probability of $x_{1}$,  p($x_{2}$) is the probability of $x_{2}$ and so forth and where mu is the Expected value of x



### The standard deviation formula is then
StdDev = $\sqrt{Variance}$




     


For rolls of the die:
- p is 1/number of sides since this is a fair die
- the possible values of x are the values on the die
- for a 6-sided die with lowest value of 1, the possible values of x are 1,2,3,4,5,6

In [32]:
# Find standard deviation
sumProbSqrdDiff = 0

for b in possibleX:
    SqrdDiff = (b - ExpectedX)**2
    ProbSqrdDiff = p * SqrdDiff
    sumProbSqrdDiff = sumProbSqrdDiff + ProbSqrdDiff

    
DistVariance = sumProbSqrdDiff
DistStdDev  = sqrt(DistVariance)
                          
  
print(f"The standard deviation of the probability distribution of one roll of a {sides}-sided die is {DistStdDev}")

The standard deviation of the probability distribution of one roll of a 20-sided die is 5.766281297335398


## Results

The results* of the simulated die rolls are as follows:

| Number of rolls in sample | Average | Sample Std Deviation |
| :- | -: | :-: |
| 5 | 11.40 | 5.3198 |
| 50 | 10.46| 5.6142 |
| 100 | 10.54 | 5.8143 |
| 200 | 10.34 | 5.7419 |
| 1000 | 10.46 | 5.8648 |
| 50000 | 10.50 |  5.7614 |

Expected value of the probability distribution is 10.50

Std deviation of the probability distribution is 5.7663 

In [33]:
print(f"*Based on simulations using a {sides}-sided die with {lowest} lowest value and {highest} highest value.");

*Based on simulations using a 20-sided die with 1 lowest value and 20 highest value.


## Discussion

I predicted that the average and standard deviation of the simulation of 100 rolls would be somewhat close to the expected value and standard deviation of the probability distribution for a 20 sided die. And, when running the simulation at n = 100, the average of 10.54 is, indeed, very close to the average for the probability distribution of 10.5.  Likewise, the simulation at n = 100 has a standard deviation of 5.8143  whereas the simulation for the probability distribution is 5.7663.

The differences can be attributed to the fact that the simulation gives actual data, whereas the probability distribution is the theoretical way that we should expect when the data is known to follow this distribution. It is also important to note that the expected value of 10.5 does not appear on a 20-sided die as a possible outcome, because the die has only discrete integers, whereas the expected value is using continuous values.

According to the Law of Large Numbers, as n gets larger, the average and standard deviation for the simulations should converge toward the expected value and standard deviation of the probability distribution for a 20 sided die. But, there is always randomness and/or bias, which is why the results of the simulations do not exactly match the probability distribution for the 20-sided die. Notice that with n = 200, the results from the simulation show an average of 10.34, which is not all that close to 10.5. Maybe the difference is just some random noise. However, the Python random number generator has the limitation of using a pseudo-random process, so maybe there is a slight non-randomness effect.

But, when n is increased to 50,000, the average and the standard deviation are both very similar to those of the probability distribution. In summary, the simulation is a good way to illustrate how as large of a sample size as possible should be used in order to achieve results that are more reflective of the true probability distribution.

If this were a real world situation in which the null hypothesis was that the population was evenly distributed between 20 outcomes, then the distributions of the sample into the 20 outcomes would need to be statistically tested (eg. using the chi-square test) to see if the sample of n = 100 represents a significantly different distribution.

Sample

The average of 100 rolls of the die with a 20-sided die is 10.54.

The standard deviation of the sample of 100 rolls of the die with a 20-sided die is 5.81433269141564.
Using the built-in standard deviation function for a sample, the standard deviation is 5.814332691415641.



The average of 5 rolls of the die with a 20-sided die is 11.4.
The standard deviation of the sample of 5 rolls of the die with a 20-sided die is 5.319774431308154.


The average of 50 rolls of the die with a 20-sided die is 10.46.
The standard deviation of the sample of 50 rolls of the die with a 20-sided die is 5.614158486381025.


The average of 200 rolls of the die with a 20-sided die is 10.34.
The standard deviation of the sample of 200 rolls of the die with a 20-sided die is 5.741885250608532.



The average of 1000 rolls of the die with a 20-sided die is 10.455.
The standard deviation of the sample of 1000 rolls of the die with a 20-sided die is 5.86484197326503.



The average of 50000 rolls of the die with a 20-sided die is 10.49568.
The standard deviation of the sample of 50000 rolls of the die with a 20-sided die is 5.761392645055505.



## Extension Exercise

### _Chi-square test_
### -------------------------
### Use the n=100 sample die rolls to represent outcomes from an experiment where subjects fall into 20 different outcomes.
### Test to see if the results are significantly different than the null hypothesis of equal frequency of all 20 possible outcomes.

In [34]:
# Import libraries
import scipy.stats as stats

In [35]:
# Set n back to 100
n = 100

In [36]:
# Create and populate a list of the expected counts for each possible outcome 

# Initialize the list
expectedCounts  = []

# Compute the (equal) number of times each possible outcome would occur
expected =  n / sides
expected = int(expected)


# Populate the list of expected counts for each outcome
for e in range(sides):
     expectedCounts.append(expected)

In [37]:
# Now, populate the list with the actual counts of the outcomes

# Call function to rerun the 100 die rolls and store in a list
# The function can be reran with identical results because the seed was recorded at the start
rollsList_100 = RollDieFunction(n)

# Initialize the list to hold the counts
actualCounts = []

# Count occurences of each outcome and populate the list
for g in range(sides):
        outcomeCount = rollsList_100.count(g + 1)
        actualCounts.append(outcomeCount)

In [38]:
# now run the chi-square test
stats.chisquare(actualCounts, expectedCounts)

Power_divergenceResult(statistic=14.8, pvalue=0.7352213365317226)

### The p value of 0.684 is greater than 0.05, so there is no evidence suggesting that the distribution of
### outcomes in the sample of 100 is different from the null hypothesis of equal likelihood for all outcomes.